### PR TITLE
Octane: Support PUT and PATCH when parsing body

### PR DESCRIPTION
**Pull request by bogdankharchenko**
Seems that PUT & PATCH method is being ignored in Octane context -- I have not checked other contexts.

### CODE REVIEW

**Comment by nunomaduro** [comment]
Can you add a test that fails before you change, and passes after your change? So we can understand what you are trying to fix?

**Comment by nunomaduro** [comment]
@bogdankharchenko Once you add the test, I will re-open the issue.

**Comment by bogdankharchenko** [comment]
@nunomaduro please run these test on latest 2.0 branch individually.

`./vendor/bin/phpunit --filter 'Laravel\\Vapor\\Tests\\Feature\\OctaneHandlerTest::test_request_body'`
`./vendor/bin/phpunit --filter 'Laravel\\Vapor\\Tests\\Feature\\LoadBalancedOctaneHandlerTest::test_request_body'`

Keep in mind, the test suite passes when ran as a whole but fails when running individually.

I suspect some gnarliness happening in one of these static methods cross test.

**Comment by nunomaduro** [comment]
Checking...

**Comment by bogdankharchenko** [comment]
> Checking...

Yeah I hope I am not wrong about this =D but I know for a fact PUT/PATCH does not work when deploying an app into prod on octane.

**Comment by taylorotwell** [comment]
PUT and PATCH do not use multipart/form-data to upload files - you need to use POST for that. Or am I missing something?

**Comment by bogdankharchenko** [comment]
> PUT and PATCH do not use multipart/form-data to upload files - you need to use POST for that. Or am I missing something?

You are right about the files.   I will update this tomorrow morning with some tests

**Comment by nunomaduro** [comment]
Feel free to re-open this ticket, once the pull request is updated.

**Pull request closed without merging**
