### PR TITLE
Preserve vendor file permissions

### PR DESCRIPTION
**Pull request by cameronmurphy**
This PR resolves an issue where the file permissions within the vendor zip archive were not being applied during extract.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I would like to avoid depending on certain binaries being available on the Lambda runtime.

**Comment by cameronmurphy** [comment]
Ordinarily I'd avoid assuming the presence of binaries but the original code assumes the presence of the `php-zip` extension which you're enabling in the custom runtime here:
https://github.com/laravel/vapor-php-build/blob/master/php74/php.Dockerfile#L390

The custom runtime also ensures the presence of the `unzip` package here:
https://github.com/laravel/vapor-php-build/blob/master/php74/php.Dockerfile#L441

I too would prefer a PHP solution but `ZipArchive` does not make it possible (I can't seem to get useful information out of `getExternalAttributesName`) to restore permissions set here:
https://github.com/laravel/vapor-cli/blob/master/src/BuildProcess/CompressVendor.php#L41

Without the correct permissions I cannot use barryvdh/laravel-snappy to generate PDFs. Is there another solution you could suggest?

**Comment by cameronmurphy** [comment]
For some context, composer tries to use `unzip` and falls back to `php-zip` only in its absence for this very reason. Would a fallback solution suffice @taylorotwell ?

https://github.com/composer/composer/issues/4471

**Comment by drfraker** [comment]
@cameronmurphy did you ever get wkhtmltopdf working on vapor?

**Comment by cameronmurphy** [comment]
@drfraker I did but fonts looked awful because Vapor runtime is missing `fontconfig`. Instead of maintaining my own fork of this runtime that includes fontconfig I migrated to pdfcrowd.com

**Comment by drfraker** [comment]
@cameronmurphy Thanks for the heads up. Glad I didn't go down that road.

**Comment by barryvdh** [comment]
I've not tried it, but following https://blog.laravel.com/vapor-adding-imagick-as-a-separate-lambda-layer you should be able to add extra layers, also for wkhtmltopdf:

wkhtmltopdf: https://github.com/brandonlim-hs/wkhtmltopdf-aws-lambda-layer
fontconfig: https://github.com/brandonlim-hs/fonts-aws-lambda-layer

That way you wouldn't need to put the binaries in the vendor folder (probably faster)

**Comment by R-Kujawa** [comment]
@barryvdh I tried your suggestion, but would result in error because just the brandonlim-hs/wkhtmltopdf-aws-lambda-layer would exceed lambda's maximum size of 250mb. 
I did manage to get this working by compiling the wkhtmltopdf binary myself with all it's dependencies and creating a lambda layer from it. I followed [this](https://tech.mybuilder.com/compiling-wkhtmltopdf-aws-lambda-with-bref-easier-than-you-think/) guide and it worked like a charm! Just a heads up, the entire process does take some time.

**Pull request merged**
