### PR TITLE
Update RDS certificate bundle for vapor-core v1

### PR DESCRIPTION
**Pull request by msiemens**
Vapor 2, which contains the latest AWS RDS PEM bundle (see 7e113666b61e4c39b9812c39e80f1ae8188164f0), is NOT compatible with Laravel 5.8. This PR backports the latest RDS PEM bundle to vapor-core 1.0 so projects that use Laravel 5.8 can have working databases, too.

On a side note, vapor-cli still does support Laravel 5.8, so I guess support for Laravel 5.8 is still desired and updating vapor-core v1 was probably just overlooked :)

### CODE REVIEW

**Comment by taylorotwell** [comment]
Vapor's requirements have always listed Laravel Framework 6.0+: https://docs.vapor.build/1.0/introduction.html#requirements

**Comment by dennisoderwald** [comment]
@taylorotwell Why not merge the pull request for users of the version? Even if it is written in the documentation, the compatibility of vapor-cli says something else.

**Comment by taylorotwell** [comment]
@dennisoderwald OK

**Comment by taylorotwell** [comment]
Just be aware we can't promise your 5.8 application will continue to run on Vapor. Things could break as it is not a supported version.

**Comment by dennisoderwald** [comment]
Thanks @taylorotwell. We are aware of this and an upgrade is already on the todo.

**Pull request merged**
