### PR TITLE
Allows access to the underlying lambda event

### PR DESCRIPTION
**Pull request by nunomaduro**
This pull request allows to have access to the underlying lambda event in your Laravel Application.

Docs: https://github.com/laravel/vapor-docs/pull/69.

```php
use Laravel\Vapor\Runtime\LambdaEvent;

Route::get('/', function (LambdaEvent $event) {
    $array = $event->toArray(); // http event
    $resourcePath = $event['requestContext.resourcePath'];

    dispatch(function(LambdaEvent $event) {
        $array = $event->toArray() // queue event
    });
});

Artisan::command('foo', function (LambdaEvent $event) {
    $array = $event->toArray(); // cli event
});
```

### CODE REVIEW

**Comment by francoisauclair911** [comment]
@nunomaduro Amazing, so eager to use this!

**Comment by taylorotwell** [comment]
@nunomaduro Can we rename `ensureEvent` and related terminology to something like `ensureLambdaEventIsBound` or something more descriptive?

**Comment by nunomaduro** [comment]
@francoisauclair911 Can you try this feature? Is released under the v2.11.0 version.

Docs: https://docs.vapor.build/1.0/projects/development.html#access-the-lambda-event-object.

**Comment by nunomaduro** [comment]
@francoisauclair911 I am sorry, the feature had to be reverted. I will get back to this as soon as possible.

**Comment by francoisauclair911** [comment]
@nunomaduro, let me know if I can help

**Comment by nunomaduro** [comment]
Because the previous implementation have caused regressions, we were forced to revert and add this feature to the backlog. Meaning that we don't have a date when it will be out.

Can you reach our support `vapor@laravel.com` so we can discuss workarounds for your issue?

**Pull request merged**
